DjangoProject/DjangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
# Import include

urlpatterns = [
    path('admin/', admin.site.urls),  # Default Django admin site
    path('', include('home.urls')),  # Include the URLs from the TestFile app
    path('movies/', include('movies.urls')),
    #path('accounts/', include('moviesStore.urls')),  # Include the URLs from the TestFile app
    path("users/", include('users.urls')),
]

DjangoProject/home/urls.py
from django.urls import path
from . import views

app_name = 'home'  # This enables namespacing in templates

urlpatterns = [
    path("", views.home, name='index'),
    path("about/", views.about, name='about'),
]

DjangoProject/movies/urls.py
from django.urls import path

from . import views

app_name = 'movies'
urlpatterns = [
    # MOVIES
    path('', views.movie_list, name='movie_list'),
    path('<int:movie_id>/', views.movie, name='movie'),

    # REVIEWS
    path('<int:movie_id>/submit_review/', views.submit_review, name='submit_review'),
    path('<int:review_id>/delete_review/', views.delete_review, name='delete_review'),
    path('<int:review_id>/edit_review/', views.edit_review, name='edit_review'),

    # SHOPPING CART
    path('cart/', views.cart, name='cart'),
    path('cart/add/<int:movie_id>/', views.add_to_cart, name='add_to_cart'),
    path('cart/remove/<int:movie_id>/', views.remove_from_cart, name='remove_from_cart'),

    # CHECKOUT
    path('checkout/', views.checkout, name='checkout'),
    path('place_order/', views.place_order, name='place_order'),
    path('order_confirmation/', views.order_confirmation, name='order_confirmation'),

    # ORDERS
    path("orders/", views.orders, name="orders"),
    path("order/<int:order_id>/", views.order_detail, name="order_detail"),

]

DjangoProject/users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


app_name = 'users'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup_view, name='signup'),


    path('forgot_password/', views.forgot_password_view, name='forgot_password'),
    path('password_reset_confirm/', views.password_reset_confirm_view, name='password_reset_confirm'),
]

DjangoProject/templates/base.html
<!DOCTYPE html>
<html>
  {% load static %}
  <head>
    <title>{{ template_data.title }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
  </head>

  <body>
    <!-- Header -->
    <nav class="p-3 navbar navbar-dark bg-dark navbar-expand-lg">
      <div class="container">
        <a class="navbar-brand" href="{% url 'home:index' %}">
          <img src="{% static 'img/logo.png' %}" alt="logo" height="40" />
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
          aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav ms-auto navbar-ml">
              <a class="nav-link" href="{% url 'movies:movie_list' %}">Movies</a>
              <a class="nav-link" href="{% url 'movies:cart' %}">Cart</a>
              <a class="nav-link" href="{% url 'home:about' %}">About</a>
              <a class="nav-link" href="{% url 'movies:orders' %}">Orders</a>
              {% if user.is_authenticated %}
                  <div class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      {{ user.username }}
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="userDropdown">
                      <li><a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a></li>
                    </ul>
                  </div>
                {% else %}
                  <a class="nav-link" href="{% url 'users:login' %}">Sign In</a>
                {% endif %}
          </div>
        </div>
      </div>
    </nav>
    <!-- Header -->

    <div>
      {% block content %}
      {% endblock content %}
    </div>

<!-- Footer -->
<footer class="bg-dark text-white py-5 mt-5">
  <div class="container-fluid px-5">
    <div class="row justify-content-center">
      <div class="col-12 col-md-4 mb-4">
        <h5 class="text-uppercase text-center">Movies Store</h5>
        <hr class="bg-light mx-auto mb-3 mt-0" style="width: 60px;" />
        <p class="text-center">
          Welcome to Movies Store, your premier online destination for a cinematic
          adventure like no other! Dive into the world of movies from the comfort of your own home with our user-friendly
          and immersive online movie store
        </p>
      </div>
      <div class="col-12 col-md-4 mb-4">
        <h5 class="text-uppercase text-center">Links</h5>
        <hr class="bg-light mx-auto mb-3 mt-0" style="width: 60px;" />
        <ul class="list-unstyled text-center">
          <li class="mb-2">
            <a class="text-white text-decoration-none footer-link" href="{% url 'home:about' %}">
              About
            </a>
          </li>
          <li class="mb-2">
            <a class="text-white text-decoration-none footer-link" href="{% url 'movies:movie_list' %}">
              Movies
            </a>
          </li>
          <li class="mb-2">
            <a class="text-white text-decoration-none footer-link" href="{% url 'movies:cart' %}">
              Cart
            </a>
          </li>
          <li class="mb-2">
            <a class="text-white text-decoration-none footer-link" href="{% url 'movies:orders' %}">
              Orders
            </a>
          </li>
        </ul>
      </div>
      <div class="col-12 col-md-4 mb-4">
        <h5 class="text-uppercase text-center">Contact</h5>
        <hr class="bg-light mx-auto mb-3 mt-0" style="width: 60px;" />
        <ul class="list-unstyled text-center">
          <li class="mb-2">
            <i class="fas fa-home me-2"></i>Georgia Tech
          </li>
          <li class="mb-2">
            <i class="fas fa-envelope me-2"></i>info@moviesstore.com
          </li>
          <li class="mb-2">
            <i class="fas fa-phone me-2"></i>+81 03-3333-3333
          </li>
        </ul>
      </div>
    </div>
    <div class="row">
      <div class="col-12 text-center mt-3">
        <p class="mb-0">&copy; 2025 Movies Store. All rights reserved.</p>
      </div>
    </div>
  </div>
</footer>
<!-- Footer -->

  </body>
</html>